service: ${file(./package.json):name}

variablesResolutionMode: 20210219
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: us-east-1
  memorySize: 1024
  timeout: 30 # match HTTP timeout
  logRetentionInDays: 14
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: ${opt:stage}
    LOG_LEVEL: ${self:custom.stages.${opt:stage}.logLevel}
    DB_URI: ${ssm:/${self:service}/${opt:stage}/db-uri~true}
    USERS_STORAGE_BUCKET_NAME: ${self:custom.stages.${opt:stage}.usersStorageBucketName}
    COGNITO_USER_POOL_ID: ${self:custom.stages.${opt:stage}.cognitoUserPoolId}
    COGNITO_REGION: ${self:provider.region}
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 128 # compress responses over 128kb

package:
  exclude: '*'
  include:
    - service/**/*.graphql
    - package.json

plugins:
  - '@haftahave/serverless-ses-template'
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-offline

functions:
  graphql-index:
    description: GraphQL handler
    handler: service/functions/graphql/index.handler
    events:
      - http:
          path: /graphql
          method: post
          cors: true
          authorizer: ${self:custom.authorizer}
      - http:
          path: /graphql
          method: get
          cors: true

  cognito-postConfirmation:
    description: Cognito Post Confirmation handler
    handler: service/functions/cognito/post-confirmation.handler
    events:
      - cognitoUserPool:
          pool: ${self:service}-${opt:stage}-user-pool # It's the pool name
          trigger: PostConfirmation
          existing: true

custom:
  cognito:
    userPoolId:
      Ref: CognitoUserPool
    userPoolArn:
      Fn::GetAtt:
        - UserStorageS3Bucket
        - Arn

  s3:
    usersStorageBucketName:
      Ref: UserStorageS3Bucket

  authorizer:
    name: Cognito
    type: COGNITO_USER_POOLS
    arn: ${self:custom.cognito.userPoolArn}

  package:
    version: ${file(./package.json):version}
    title: ${file(./package.json):title}

  stages:
    local:
      usersStorageBucketName: ${env:USERS_STORAGE_BUCKET_NAME}
      cognitoUserPoolId: ${env:COGNITO_USER_POOL_ID}
      logLevel: debug
    development:
      usersStorageBucketName: ${self:custom.s3.usersStorageBucketName}
      cognitoUserPoolId: ${self:custom.cognito.userPoolId}
      logLevel: debug
    staging:
      usersStorageBucketName: ${self:custom.s3.usersStorageBucketName}
      cognitoUserPoolId: ${self:custom.cognito.userPoolId}
      logLevel: error
    production:
      usersStorageBucketName: ${self:custom.s3.usersStorageBucketName}
      cognitoUserPoolId: ${self:custom.cognito.userPoolId}
      logLevel: error

  prune:
    automatic: true
    number: 3

resources:
  Resources:
    - ${file(./configs/resources/storage.yml)}
    - ${file(./configs/resources/auth.yml)}
