service: ${file(./package.json):name}

variablesResolutionMode: 20210326
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage}
  region: us-east-1
  memorySize: 1024
  timeout: 30 # match HTTP timeout
  logRetentionInDays: 14
  lambdaHashingVersion: 20201221
  iamRoleStatements: ${file(./configs/iam/role/statements.yml)}
  environment: ${file(./configs/environment.yml)}
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 128 # compress responses over 128kb

package:
  exclude: '*'
  include:
    - service/**/*.graphql
    - package.json

plugins:
  - '@haftahave/serverless-ses-template'
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-offline

functions: ${file(./configs/functions.yml)}

custom: ${file(./configs/custom.yml)}

resources:
  - ${file(./configs/resources/responses.yml)}
  - ${file(./configs/resources/storage.yml)}
  - ${file(./configs/resources/auth.yml)}
