# Allow functions to send emails through SES
- Resource:
    Fn::Join:
      - ':'
      - - arn:aws:ses
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - identity/*
  Effect: Allow
  Action:
    - ses:SendEmail
    - ses:SendTemplatedEmail
    - ses:SendRawEmail
    - ses:SendBulkTemplatedEmail

# Allow functions to manage Cognito users
- Resource:
    Fn::GetAtt:
      - CognitoUserPool
      - Arn
  Effect: Allow
  Action:
    - cognito-idp:AdminCreateUser
    - cognito-idp:AdminDeleteUser

# Allow functions to act on Users S3 bucket
- Resource: # Just the bucket
    Fn::GetAtt:
      - UsersStorageS3Bucket
      - Arn
  Effect: Allow
  Action:
    - s3:ListBucket

- Resource: # Any object in the bucket
    Fn::Join:
      - '/'
      - - Fn::GetAtt:
            - UsersStorageS3Bucket
            - Arn
        - '*'
  Effect: Allow
  Action:
    - s3:PutObjectAcl
    - s3:PutObject
    - s3:GetObjectAcl
    - s3:GetObject
    - s3:DeleteObject
