NODE_ENV: ${opt:stage}
DB_URI: ${self:custom.stages.${opt:stage}.dbUri}
LOG_LEVEL: ${self:custom.stages.${opt:stage}.logLevel}
USERS_STORAGE_BUCKET_NAME: ${self:custom.stages.${opt:stage}.usersStorageBucketName}
COGNITO_USER_POOL_ID: ${self:custom.stages.${opt:stage}.cognitoUserPoolId}
COGNITO_REGION: ${self:provider.region}
